"""Closed vocabularies for Aster Station schema version 0.1.0."""

from __future__ import annotations

from enum import StrEnum


class OperatingMode(StrEnum):
    STABLE = "STABLE"
    LOAD_CHANGE = "LOAD_CHANGE"
    DISTURBED = "DISTURBED"
    RECOVERY = "RECOVERY"
    STABILIZED = "STABILIZED"
    UNKNOWN = "UNKNOWN"


class ComponentState(StrEnum):
    AVAILABLE = "AVAILABLE"
    DEGRADED = "DEGRADED"
    UNAVAILABLE = "UNAVAILABLE"
    STARTING = "STARTING"
    RECOVERING = "RECOVERING"
    SUSPECT = "SUSPECT"
    UNKNOWN = "UNKNOWN"


class ObservationStatus(StrEnum):
    NORMAL = "NORMAL"
    WATCH = "WATCH"
    ABNORMAL = "ABNORMAL"
    MISSING = "MISSING"
    CONFLICTING = "CONFLICTING"


class ChannelQuality(StrEnum):
    GOOD = "GOOD"
    SUSPECT = "SUSPECT"
    NOISY = "NOISY"
    UNAVAILABLE = "UNAVAILABLE"


class StateVariable(StrEnum):
    HEAT_SOURCE_LEVEL = "heat_source_level"
    PRIMARY_FLOW = "primary_flow"
    PRIMARY_THERMAL_STATE = "primary_thermal_state"
    PRIMARY_INVENTORY = "primary_inventory"
    TRANSFER_EFFICIENCY = "transfer_efficiency"
    SECONDARY_FLOW = "secondary_flow"
    SECONDARY_INVENTORY = "secondary_inventory"
    STEAM_STATE = "steam_state"
    CONDENSER_FUNCTION = "condenser_function"
    HEAT_REJECTION = "heat_rejection"
    TURBINE_OUTPUT = "turbine_output"
    ELECTRICAL_OUTPUT = "electrical_output"
    LOAD_DEMAND = "load_demand"
    SUPPORT_POWER = "support_power"


class FaultFamily(StrEnum):
    """Injected faults only; benign LOAD_TRANSIENT is intentionally absent."""

    SENSOR_DRIFT = "SENSOR_DRIFT"
    SENSOR_STUCK = "SENSOR_STUCK"
    SENSOR_NOISE = "SENSOR_NOISE"
    PUMP_DEGRADATION = "PUMP_DEGRADATION"
    PUMP_TRIP = "PUMP_TRIP"
    VALVE_LAG = "VALVE_LAG"
    VALVE_STUCK = "VALVE_STUCK"
    TRANSFER_EFFICIENCY_LOSS = "TRANSFER_EFFICIENCY_LOSS"
    FLOW_IMBALANCE = "FLOW_IMBALANCE"
    SUPPORT_POWER_INTERRUPTION = "SUPPORT_POWER_INTERRUPTION"
    ABSTRACT_INVENTORY_LOSS = "ABSTRACT_INVENTORY_LOSS"


class ScenarioDriver(StrEnum):
    STEADY_OPERATION = "STEADY_OPERATION"
    LOAD_TRANSIENT = "LOAD_TRANSIENT"


class ActionLabel(StrEnum):
    VERIFY_REDUNDANT_CHANNEL = "VERIFY_REDUNDANT_CHANNEL"
    COMPARE_RELATED_TRENDS = "COMPARE_RELATED_TRENDS"
    FLAG_SENSOR_SUSPECT = "FLAG_SENSOR_SUSPECT"
    REQUEST_COMPONENT_INSPECTION = "REQUEST_COMPONENT_INSPECTION"
    SELECT_SYNTHETIC_STANDBY_TRAIN = "SELECT_SYNTHETIC_STANDBY_TRAIN"
    REDUCE_SIMULATED_LOAD = "REDUCE_SIMULATED_LOAD"
    ENTER_SIMULATED_STABLE_STATE = "ENTER_SIMULATED_STABLE_STATE"
    CONTINUE_MONITORING = "CONTINUE_MONITORING"
    INSUFFICIENT_EVIDENCE = "INSUFFICIENT_EVIDENCE"


class DiagnosisStatus(StrEnum):
    DIAGNOSED = "DIAGNOSED"
    NO_FAULT = "NO_FAULT"
    UNRESOLVED = "UNRESOLVED"


class AbstentionReason(StrEnum):
    INSUFFICIENT_EVIDENCE = "INSUFFICIENT_EVIDENCE"


class PlantVariant(StrEnum):
    ASTER_A = "ASTER-A"
    ASTER_B = "ASTER-B"
    ASTER_C = "ASTER-C"


class SeverityBand(StrEnum):
    LOW = "LOW"
    MEDIUM = "MEDIUM"
    HIGH = "HIGH"


class AsterSubsystem(StrEnum):
    """Closed subsystem vocabulary used by structured incident summaries."""

    HEAT_SOURCE = "HEAT_SOURCE"
    PRIMARY_LOOP = "PRIMARY_LOOP"
    TRANSFER_UNIT = "TRANSFER_UNIT"
    SECONDARY_LOOP = "SECONDARY_LOOP"
    TURBINE_GENERATOR = "TURBINE_GENERATOR"
    CONDENSER_AND_REJECTION = "CONDENSER_AND_REJECTION"
    SUPPORT_POWER = "SUPPORT_POWER"
    INSTRUMENTATION = "INSTRUMENTATION"


class ObservedTrend(StrEnum):
    """Bounded qualitative trend labels; no free-form summary text is stored."""

    STABLE = "STABLE"
    RISING = "RISING"
    FALLING = "FALLING"
    MIXED = "MIXED"
    UNKNOWN = "UNKNOWN"


class EventType(StrEnum):
    """Visible event categories that never disclose an injected fault label."""

    OPERATING_MODE_CHANGED = "OPERATING_MODE_CHANGED"
    TARGET_CHANGED = "TARGET_CHANGED"
    COMPONENT_STATE_CHANGED = "COMPONENT_STATE_CHANGED"
    OBSERVATION_CHANGED = "OBSERVATION_CHANGED"
    CHANNEL_QUALITY_CHANGED = "CHANNEL_QUALITY_CHANGED"
    CHANNEL_DISAGREEMENT = "CHANNEL_DISAGREEMENT"
    COMMAND_RECORDED = "COMMAND_RECORDED"
    COMMAND_POSITION_MISMATCH = "COMMAND_POSITION_MISMATCH"
    ACTION_APPLIED = "ACTION_APPLIED"
    BENIGN_NOTE = "BENIGN_NOTE"


class EvidenceSlot(StrEnum):
    STABLE_OPERATION = "STABLE_OPERATION"
    COORDINATED_LOAD_RESPONSE = "COORDINATED_LOAD_RESPONSE"
    CHANNEL_DISAGREEMENT = "CHANNEL_DISAGREEMENT"
    RELATED_STATE_STABLE = "RELATED_STATE_STABLE"
    CHANNEL_FROZEN = "CHANNEL_FROZEN"
    CORRELATED_STATE_CHANGE = "CORRELATED_STATE_CHANGE"
    RAPID_INCONSISTENT_READINGS = "RAPID_INCONSISTENT_READINGS"
    COMPONENT_HEALTH_DECLINING = "COMPONENT_HEALTH_DECLINING"
    FLOW_DECLINING = "FLOW_DECLINING"
    DEPENDENT_TREND_DELAY = "DEPENDENT_TREND_DELAY"
    COMPONENT_UNAVAILABLE = "COMPONENT_UNAVAILABLE"
    STANDBY_AVAILABLE = "STANDBY_AVAILABLE"
    COMMAND_POSITION_MISMATCH = "COMMAND_POSITION_MISMATCH"
    MISMATCH_RESOLVED = "MISMATCH_RESOLVED"
    MISMATCH_PERSISTED = "MISMATCH_PERSISTED"
    UPSTREAM_DOWNSTREAM_DIVERGENCE = "UPSTREAM_DOWNSTREAM_DIVERGENCE"
    SECONDARY_TREND_MISMATCH = "SECONDARY_TREND_MISMATCH"
    SUPPORT_BUS_CHANGE = "SUPPORT_BUS_CHANGE"
    MAPPED_COMPONENT_CHANGE = "MAPPED_COMPONENT_CHANGE"
    INVENTORY_TREND_DECLINING = "INVENTORY_TREND_DECLINING"
    MULTIPLE_CHANNELS_AGREE = "MULTIPLE_CHANNELS_AGREE"
    MISSING_DECISIVE_EVIDENCE = "MISSING_DECISIVE_EVIDENCE"
    CONFLICTING_OBSERVATIONS = "CONFLICTING_OBSERVATIONS"


class SplitName(StrEnum):
    IID_TRAIN = "iid_train"
    IID_VALIDATION = "iid_validation"
    IID_TEST = "iid_test"
    TEMPLATE_TEST = "template_test"
    COMPONENT_TEST = "component_test"
    SEVERITY_TEST = "severity_test"
    COMPOSITION_TEST = "composition_test"
    COUNTERFACTUAL_TEST = "counterfactual_test"
    NOISE_TEST = "noise_test"


class TaskName(StrEnum):
    CONTINUE_LOG = "continue_log"
    FAULT_FAMILY = "fault_family"
    EXTRACT_EVIDENCE = "extract_evidence"
    NEXT_ACTION = "next_action"
    INCIDENT_SUMMARY = "incident_summary"
    COUNTERFACTUAL_COMPARE = "counterfactual_compare"


class CounterfactualChange(StrEnum):
    """Structured conclusion fields a matched counterfactual may change."""

    DIAGNOSIS_STATUS = "DIAGNOSIS_STATUS"
    FAULT_LABELS = "FAULT_LABELS"
    EVIDENCE_SLOTS = "EVIDENCE_SLOTS"
    IMMEDIATE_ACTION = "IMMEDIATE_ACTION"
