"""Phase 2 deterministic synthetic Aster simulation entry points."""

from .content_guard import (
    ContentFinding,
    ProhibitedContentError,
    assert_no_prohibited_content,
    scan_prohibited_content,
)
from .core import (
    GENERATOR_VERSION,
    SimulationTrace,
    UnsupportedScenarioError,
    build_load_transient_scenario,
    build_pump_degradation_scenario,
    build_pump_trip_scenario,
    build_sensor_drift_scenario,
    build_sensor_noise_scenario,
    build_sensor_stuck_load_scenario,
    build_stable_scenario,
    build_valve_lag_scenario,
    build_valve_stuck_scenario,
    dependency_map_context_for,
    generate_trace,
)
from .variants import (
    ASTER_A_SPEC,
    ASTER_B_SPEC,
    ASTER_C_SPEC,
    VARIANT_REGISTRY,
    AsterVariantSpec,
    ChannelRole,
    ChannelSpec,
    ComponentRole,
    ComponentSpec,
    DependencyLinkSpec,
    get_variant_spec,
)

__all__ = [
    "ASTER_A_SPEC",
    "ASTER_B_SPEC",
    "ASTER_C_SPEC",
    "GENERATOR_VERSION",
    "VARIANT_REGISTRY",
    "AsterVariantSpec",
    "ChannelRole",
    "ChannelSpec",
    "ComponentRole",
    "ComponentSpec",
    "ContentFinding",
    "DependencyLinkSpec",
    "ProhibitedContentError",
    "SimulationTrace",
    "UnsupportedScenarioError",
    "assert_no_prohibited_content",
    "build_load_transient_scenario",
    "build_pump_degradation_scenario",
    "build_pump_trip_scenario",
    "build_sensor_drift_scenario",
    "build_sensor_noise_scenario",
    "build_sensor_stuck_load_scenario",
    "build_stable_scenario",
    "build_valve_lag_scenario",
    "build_valve_stuck_scenario",
    "dependency_map_context_for",
    "generate_trace",
    "get_variant_spec",
    "scan_prohibited_content",
]
